Magazin_Bijoux/Controllers/API/CultureController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using System;
namespace Magazin_Bijoux.Controllers
{
    public class CultureController : Controller
    {
        [HttpPost]
        public IActionResult SetCulture(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );
            return LocalRedirect(returnUrl);
        }
    }
}

Magazin_Bijoux/Controllers/CartItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Magazin_Bijoux.Data;
using Magazin_Bijoux.Models;
using Microsoft.Extensions.Localization;

namespace Magazin_Bijoux.Controllers
{
    public class CartItemsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IStringLocalizer<SharedResource> _sharedLocalizer;

        public string ShoppingCartId { get; set; }

        public CartItemsController(ApplicationDbContext context, IStringLocalizer<SharedResource> sharedLocalizer)
        {
            _context = context;
            _sharedLocalizer = sharedLocalizer;
        }
        public const string CartSessionKey = "CartId";
 
        // GET: CartItems
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.CartItem.Include(c => c.product);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: CartItems/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cartItem = await _context.CartItem
                .Include(c => c.product)
                .FirstOrDefaultAsync(m => m.itemId == id);
            if (cartItem == null)
            {
                return NotFound();
            }

            return View(cartItem);
        }

        // GET: CartItems/Create
        public IActionResult Create()
        {
            ViewData["productId"] = new SelectList(_context.Product, "id", "id");
            return View();
        }

        // POST: CartItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("itemId,cartId,quantity,dateCreated,productId")] CartItem cartItem)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cartItem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["productId"] = new SelectList(_context.Product, "id", "id", cartItem.productId);
            return View(cartItem);
        }

        // GET: CartItems/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cartItem = await _context.CartItem.FindAsync(id);
            if (cartItem == null)
            {
                return NotFound();
            }
            ViewData["productId"] = new SelectList(_context.Product, "id", "id", cartItem.productId);
            return View(cartItem);
        }

        // POST: CartItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("itemId,cartId,quantity,dateCreated,productId")] CartItem cartItem)
        {
            if (id != cartItem.itemId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cartItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CartItemExists(cartItem.itemId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["productId"] = new SelectList(_context.Product, "id", "id", cartItem.productId);
            return View(cartItem);
        }

        // GET: CartItems/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cartItem = await _context.CartItem
                .Include(c => c.product)
                .FirstOrDefaultAsync(m => m.itemId == id);
            if (cartItem == null)
            {
                return NotFound();
            }

            return View(cartItem);
        }

        // POST: CartItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var cartItem = await _context.CartItem.FindAsync(id);
            _context.CartItem.Remove(cartItem);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CartItemExists(string id)
        {
            return _context.CartItem.Any(e => e.itemId == id);
        }
        public string GetCartId()
        {
            if (!HttpContext.Items.ContainsKey(CartSessionKey))
            {
                if (!string.IsNullOrWhiteSpace(HttpContext.User.Identity.Name))
                {
                    HttpContext.Items.Add(CartSessionKey, HttpContext.User.Identity.Name);
                }
                else
                {
                    // Generate a new random GUID using System.Guid class.     
                    Guid tempCartId = Guid.NewGuid();
                    HttpContext.Items.Add(CartSessionKey, tempCartId);
                }
            }
            return HttpContext.Items[CartSessionKey].ToString();
        }
        public List<CartItem> GetCartItems()
        {

            ShoppingCartId = GetCartId();

            return _context.CartItem.Where(
                c => c.cartId == ShoppingCartId).Include(c=>c.product).ToList();
        }
        public ViewResult Cart()
        {
            var cartContext = GetCartItems();
            foreach (var item in cartContext)
            {
                item.product.name = _sharedLocalizer[item.product.name];
                item.product.details = _sharedLocalizer[item.product.details];
                item.product.color = _sharedLocalizer[item.product.color];
            }
            return View(cartContext);
        }

        public void AddToCart(string id)
        {
            // Retrieve the product from the database.           
            ShoppingCartId = GetCartId();

            var cartItem = _context.CartItem.SingleOrDefault(
                c => c.cartId == ShoppingCartId
                && c.productId == id);
            if (cartItem == null)
            {
                // Create a new cart item if no cart item exists.                 
                cartItem = new CartItem
                {
                    itemId = Guid.NewGuid().ToString(),
                    productId = id,
                    cartId = ShoppingCartId,
                    product = _context.Product.SingleOrDefault(
                   p => p.id == id),
                    quantity = 1,
                    dateCreated = DateTime.Now
                };

                _context.CartItem.Add(cartItem);
            }
            else
            {
                // If the item does exist in the cart,                  
                // then add one to the quantity.                 
                cartItem.quantity++;
            }
            _context.SaveChanges();
        }
        public void RemoveFromCart(string id)
        {
            ShoppingCartId = GetCartId();
            var cartItem = _context.CartItem.SingleOrDefault(
                c => c.cartId == ShoppingCartId
                && c.productId == id);
            cartItem.quantity--;
            if (cartItem.quantity <= 0) _context.CartItem.Remove(cartItem);
            _context.SaveChanges();
        }
        public async Task<IActionResult> AddToCartAndReturn(string id, string action, string controller, int quantity, bool hasParameter)
        {
            for (int i = 0; i < quantity; i++)
            {
                AddToCart(id);
            }
            if (hasParameter == true)
                return RedirectToAction(action, controller, new { id = id });
            return RedirectToAction(action, controller);
        }
        public async Task<IActionResult> RemoveFromCartAndReturn(string id, string action, string controller, bool hasParameter)
        {
            RemoveFromCart(id);
            if (hasParameter == true)
                return RedirectToAction(action, controller, new { id = id });
            return RedirectToAction(action, controller);
        }
        public async Task<IActionResult> DeleteFromCart(string id, string action, string controller)
        {
            var cartItem = await _context.CartItem.FindAsync(id);
            _context.CartItem.Remove(cartItem);
            await _context.SaveChangesAsync();
            return RedirectToAction(action, controller);
        }
    }
}

Magazin_Bijoux/Views/Shared/_LanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
    .Select(c => new SelectListItem { Value = c.Name, Text = Localizer.GetString(c.Name) })
    .ToList();
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}{Context.Request.QueryString}";
}
<style>
    .c-form{
        padding: 0px;
    }
    .c-select{
        border: 1px solid transparent;
        border-color: transparent;
        background-color: transparent;
        font-size: 18px;
        color: white;
    }
    .c-select:focus {
        color: black;
    }
</style>
<div title="@Localizer[" Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage"
            asp-controller="Culture"
            asp-action="SetCulture"
            asp-route-returnUrl="@returnUrl"
            method="post"
            class="form-horizontal nav-link text-dark c-form"
            role="form"
            >
        <select name="culture"
                onchange="this.form.submit();"
                asp-for="@requestCulture.RequestCulture.UICulture.Name"
                asp-items="cultureItems"
                class="c-select"
                >
        </select>
    </form>
</div>

Magazin_Bijoux/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Magazin_Bijoux</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div class="header__logo">
            <a asp-area="" asp-controller="Home" asp-action="Index"><img src="~/MOFT-LOGO.png" alt="logo" /></a>
        </div>
        <div class="header__nav">
            @await Html.PartialAsync("_LanguagePartial")
            <partial name="_LoginPartial" />
            <a asp-area="" asp-controller="Home" asp-action="Shop">@localizer["shop"]</a>
            <a asp-area="" asp-controller="Home" asp-action="About">@localizer["about"]</a>
            @if (SignInManager.IsSignedIn(User))
            {
                <div class="header__cart">
                    <a asp-area="" asp-controller="CartItems" asp-action="Cart"><img src="~/Icons/white-shopping-cart-icon.jpg" alt="cart" /></a>
                </div>
            }
            else
            {
                <div class="header__cart">
                    <a asp-area="Identity" asp-page="/Account/Login"><img src="~/Icons/white-shopping-cart-icon.jpg" alt="cart" /></a>
                </div>
            }
            @*<partial name="_CartMenuPartial"/>*@

        </div>
    </header>
    <div class="header__image">
        <img src="~/Header_BG.png" alt="Header" />
    </div>


    <div class="container" style="margin-top: 20px; margin-bottom: 20px;">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>
        <div class="footer__left">
            <a class="white_link" asp-area="" asp-controller="Home" asp-action="LegalPage">FAQ</a>
            <a class="white_link" asp-area="" asp-controller="Home" asp-action="LegalPage">@localizer["legal page"]</a>
        </div>
        <div class="footer__right">
            <div class="footer__phone">
                <img src="~/Icons/CallIcon.png" alt="phone" />
            </div>
            <div class="footer__contacts">
                <div>MOFT-BIJOUX@gmail.com</div>
                <div>+353-989-898-98</div>
            </div>
            <div class="footer__links">
                <div class="footer__link">
                    <a href="https://www.facebook.com"><img src="~/Icons/Facebook1024.png" alt="facebook" /></a>
                </div>
                <div class="footer__link">
                    <a href="https://www.instagram.com/"><img src="~/Icons/Instagram-Logo.wine.png" alt="instagram.png" /></a>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>