Magazin_Bijoux/Models/CartItem.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Magazin_Bijoux.Models
{
    public class CartItem
    {
        [Key]
        public string itemId { get; set; }

        public string cartId { get; set; }

        [Range(0,1000)]
        public int quantity { get; set; }
        public DateTime dateCreated { get; set; }
        public string productId { get; set; }

        public virtual Product product { get; set; }
        
        public float totalPrice { get; set; }


        public float getTotalPrice()
        {
            this.totalPrice = quantity * product.price;
            return totalPrice;
        }
    }
}

Magazin_Bijoux/Controllers/CartItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Magazin_Bijoux.Data;
using Magazin_Bijoux.Models;
using Microsoft.Extensions.Localization;

namespace Magazin_Bijoux.Controllers
{
    public class CartItemsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IStringLocalizer<SharedResource> _sharedLocalizer;

        public string ShoppingCartId { get; set; }

        public CartItemsController(ApplicationDbContext context, IStringLocalizer<SharedResource> sharedLocalizer)
        {
            _context = context;
            _sharedLocalizer = sharedLocalizer;
        }
        public const string CartSessionKey = "CartId";
 
        // GET: CartItems
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.CartItem.Include(c => c.product);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: CartItems/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cartItem = await _context.CartItem
                .Include(c => c.product)
                .FirstOrDefaultAsync(m => m.itemId == id);
            if (cartItem == null)
            {
                return NotFound();
            }

            return View(cartItem);
        }

        // GET: CartItems/Create
        public IActionResult Create()
        {
            ViewData["productId"] = new SelectList(_context.Product, "id", "id");
            return View();
        }

        // POST: CartItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("itemId,cartId,quantity,dateCreated,productId")] CartItem cartItem)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cartItem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["productId"] = new SelectList(_context.Product, "id", "id", cartItem.productId);
            return View(cartItem);
        }

        // GET: CartItems/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cartItem = await _context.CartItem.FindAsync(id);
            if (cartItem == null)
            {
                return NotFound();
            }
            ViewData["productId"] = new SelectList(_context.Product, "id", "id", cartItem.productId);
            return View(cartItem);
        }

        // POST: CartItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("itemId,cartId,quantity,dateCreated,productId")] CartItem cartItem)
        {
            if (id != cartItem.itemId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cartItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CartItemExists(cartItem.itemId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["productId"] = new SelectList(_context.Product, "id", "id", cartItem.productId);
            return View(cartItem);
        }

        // GET: CartItems/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cartItem = await _context.CartItem
                .Include(c => c.product)
                .FirstOrDefaultAsync(m => m.itemId == id);
            if (cartItem == null)
            {
                return NotFound();
            }

            return View(cartItem);
        }

        // POST: CartItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var cartItem = await _context.CartItem.FindAsync(id);
            _context.CartItem.Remove(cartItem);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CartItemExists(string id)
        {
            return _context.CartItem.Any(e => e.itemId == id);
        }
        public string GetCartId()
        {
            if (!HttpContext.Items.ContainsKey(CartSessionKey))
            {
                if (!string.IsNullOrWhiteSpace(HttpContext.User.Identity.Name))
                {
                    HttpContext.Items.Add(CartSessionKey, HttpContext.User.Identity.Name);
                }
                else
                {
                    // Generate a new random GUID using System.Guid class.     
                    Guid tempCartId = Guid.NewGuid();
                    HttpContext.Items.Add(CartSessionKey, tempCartId);
                }
            }
            return HttpContext.Items[CartSessionKey].ToString();
        }
        public List<CartItem> GetCartItems()
        {

            ShoppingCartId = GetCartId();

            return _context.CartItem.Where(
                c => c.cartId == ShoppingCartId).Include(c=>c.product).ToList();
        }
        public ViewResult Cart()
        {
            var cartContext = GetCartItems();
            foreach (var item in cartContext)
            {
                item.product.name = _sharedLocalizer[item.product.name];
                item.product.details = _sharedLocalizer[item.product.details];
                item.product.color = _sharedLocalizer[item.product.color];
            }
            return View(cartContext);
        }

        public void AddToCart(string id)
        {
            // Retrieve the product from the database.           
            ShoppingCartId = GetCartId();

            var cartItem = _context.CartItem.SingleOrDefault(
                c => c.cartId == ShoppingCartId
                && c.productId == id);
            if (cartItem == null)
            {
                // Create a new cart item if no cart item exists.                 
                cartItem = new CartItem
                {
                    itemId = Guid.NewGuid().ToString(),
                    productId = id,
                    cartId = ShoppingCartId,
                    product = _context.Product.SingleOrDefault(
                   p => p.id == id),
                    quantity = 1,
                    dateCreated = DateTime.Now
                };

                _context.CartItem.Add(cartItem);
            }
            else
            {
                // If the item does exist in the cart,                  
                // then add one to the quantity.                 
                cartItem.quantity++;
            }
            _context.SaveChanges();
        }
        public void RemoveFromCart(string id)
        {
            ShoppingCartId = GetCartId();
            var cartItem = _context.CartItem.SingleOrDefault(
                c => c.cartId == ShoppingCartId
                && c.productId == id);
            cartItem.quantity--;
            if (cartItem.quantity <= 0) _context.CartItem.Remove(cartItem);
            _context.SaveChanges();
        }
        public async Task<IActionResult> AddToCartAndReturn(string id, string action, string controller, int quantity, bool hasParameter)
        {
            for (int i = 0; i < quantity; i++)
            {
                AddToCart(id);
            }
            if (hasParameter == true)
                return RedirectToAction(action, controller, new { id = id });
            return RedirectToAction(action, controller);
        }
        public async Task<IActionResult> RemoveFromCartAndReturn(string id, string action, string controller, bool hasParameter)
        {
            RemoveFromCart(id);
            if (hasParameter == true)
                return RedirectToAction(action, controller, new { id = id });
            return RedirectToAction(action, controller);
        }
        public async Task<IActionResult> DeleteFromCart(string id, string action, string controller)
        {
            var cartItem = await _context.CartItem.FindAsync(id);
            _context.CartItem.Remove(cartItem);
            await _context.SaveChangesAsync();
            return RedirectToAction(action, controller);
        }
    }
}

Magazin_Bijoux/Controllers/MailController.cs
using Magazin_Bijoux.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

[Route("api/[controller]")]
[ApiController]
public class MailController : ControllerBase
{
    private readonly IMailService mailService;
    public MailController(IMailService mailService)
    {
        this.mailService = mailService;
    }

    [HttpPost("send")]
    public async Task<IActionResult> SendMail([FromForm] MailRequest request)
    {
        try
        {
            await mailService.SendEmailAsync(request);
            return Ok();
        }
        catch (Exception ex)
        {
            throw;
        }
    }

    [HttpPost("welcome")]
    public async Task<IActionResult> SendWelcomeMail([FromForm] WelcomeRequest request)
    {
        try
        {
            await mailService.SendWelcomeEmailAsync(request);
            return RedirectToAction("Cart", "CartItems");
        }
        catch (Exception ex)
        {
            throw;
        }
    }
    public async Task<IActionResult> SendPurchaseMail([FromForm] PurchaseRequest request)
    {
        try
        {
            await mailService.SendPurchaseEmailAsync(request);
            return RedirectToAction("Cart", "CartItems");
        }
        catch (Exception ex)
        {
            throw;
        }
    }
}

Magazin_Bijoux/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Magazin_Bijoux.Data;
using Magazin_Bijoux.Models;
using Microsoft.Extensions.Localization;

namespace Magazin_Bijoux.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IStringLocalizer<SharedResource> _sharedLocalizer;

        public ProductsController(ApplicationDbContext context, IStringLocalizer<SharedResource> sharedLocalizer)
        {
            _context = context;
            _sharedLocalizer = sharedLocalizer;
        }

        public IActionResult GetTime()
        {
            var currentTime = DateTime.Now.ToString("HH:mm:ss");
            return Json(currentTime);
        }
        // GET: Products
        public async Task<IActionResult> Index()
        {
            return View(await _context.Product.ToListAsync());
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }
        public async Task<IActionResult> Product(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.id == id);
            if (product == null)
            {
                return NotFound();
            }

            product.name = _sharedLocalizer[product.name];
            product.details = _sharedLocalizer[product.details];
            product.color = _sharedLocalizer[product.color];

            return View(product);
        }
        public void Decrement(string id)
        {
            ViewBag.quantity=1;
        }
        public async Task<IActionResult> Increment(string id)
        {
            ViewBag.quantity++;
            return RedirectToAction("Product", id);
        }
        // GET: Products/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,name,details,size,color,price,imageURL")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("id,name,details,size,color,price,imageURL")] Product product)
        {
            if (id != product.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var product = await _context.Product.FindAsync(id);
            _context.Product.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(string id)
        {
            return _context.Product.Any(e => e.id == id);
        }
        void DecrementCount()
        {
            if (ViewBag.quantity > 1)
                ViewBag.quantity--;
        }
    }
}

Magazin_Bijoux/Views/CartItems/Cart.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@model IEnumerable<Magazin_Bijoux.Models.CartItem>

@{
    ViewData["Title"] = localizer["title"] ;
    string productList = "";
    float totalPrice = 0;
}
<head>
    <link rel="stylesheet" href="~/css/home.css" />
    <link rel="stylesheet" href="~/css/Cart.css" />
</head>

<h3 class="fancy-font">@localizer["my cart"]</h3>
<div>
    @foreach (var item in Model)
    {
        totalPrice += item.getTotalPrice();
        productList += item.quantity+" "+item.product.name+": $"+item.getTotalPrice()+"<br>";
        <hr />
        <div id="cartitem-container">
            <a class="product_link" asp-controller="Products" asp-action="Product" asp-route-id="@item.product.id">
                    <img class="small_cart_img" src=@String.Format("/Product_img280x373/{0}.png", item.product.imageURL) />
                    <div style="margin-left: 17px; margin-top: 20px;"class="fancy-font f-size">
                        <p>@Html.DisplayFor(modelItem => item.product.name)</p>
                        <p>$@Html.DisplayFor(modelItem => item.product.price)</p>
                    </div>
            </a>
            <div>
                <div id="cart-counter" class="fancy-font f-size">
                    <form asp-controller="CartItems" asp-action="RemoveFromCartAndReturn" asp-route-id="@item.productId">
                        <input type="hidden" name="action" value="Cart" />
                        <input type="hidden" name="controller" value="CartItems" />
                        <input type="hidden" name="hasParameter" value="false" />
                        <div class="form-group" style="text-align:center">
                            <input type="submit" value="-" />
                        </div>
                    </form>

                    <p style="display: flex; align-items: center;">@Html.DisplayFor(modelItem => item.quantity)</p>

                    <form asp-controller="CartItems" asp-action="AddToCartAndReturn" asp-route-id="@item.productId">
                        <input type="hidden" name="action" value="Cart" />
                        <input type="hidden" name="controller" value="CartItems" />
                        <input type="hidden" name="quantity" value=1 />
                        <input type="hidden" name="hasParameter" value="false" />
                        <div class="form-group" >
                            <input type="submit" value="+" />
                        </div>
                    </form>
                    <p style="display: flex; align-items: center;">$@item.getTotalPrice()</p>
                </div>
            </div>

            <form asp-controller="CartItems" asp-action="DeleteFromCart" asp-route-id="@item.itemId">
                <input type="hidden" name="action" value="Cart" />
                <input type="hidden" name="controller" value="CartItems" />
                <input type="hidden" name="hasParameter" value="false" />
                <div class="form-group" style="font-size:20px;">
                    <input type="submit" value="X" />
                </div>
            </form>
        </div>
    }
    <hr />
    <p class="fancy-font f-size">Total: $@totalPrice</p>

    <form asp-controller="Mail" asp-action="SendPurchaseMail">
        <input type="hidden" name="UserName" value="@UserManager.GetUserAsync(User).Result.UserName" />
        <input type="hidden" name="ToEmail" value="@UserManager.GetUserAsync(User).Result.Email" />
        <input type="hidden" name="ItemList" value="@productList" />
        <input type="hidden" name="TotalPrice" value="@totalPrice" />
        <div class="form-group">
            <input type="submit" value=@localizer["finish purchase"] class="card__button btn-primary" />
        </div>
    </form>
</div>

Magazin_Bijoux/Views/CartItems/Create.cshtml
@model Magazin_Bijoux.Models.CartItem

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CartItem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="itemId" class="control-label"></label>
                <input asp-for="itemId" class="form-control" />
                <span asp-validation-for="itemId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cartId" class="control-label"></label>
                <select asp-for="cartId" class ="form-control" asp-items="ViewBag.cartId"></select>
            </div>
            <div class="form-group">
                <label asp-for="quantity" class="control-label"></label>
                <input asp-for="quantity" class="form-control" />
                <span asp-validation-for="quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="dateCreated" class="control-label"></label>
                <input asp-for="dateCreated" class="form-control" />
                <span asp-validation-for="dateCreated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="productId" class="control-label"></label>
                <select asp-for="productId" class ="form-control" asp-items="ViewBag.productId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Magazin_Bijoux/Views/CartItems/Delete.cshtml
@model Magazin_Bijoux.Models.CartItem

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CartItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.dateCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.dateCreated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.product)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.product.id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="itemId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Magazin_Bijoux/Views/CartItems/Details.cshtml
@model Magazin_Bijoux.Models.CartItem

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>CartItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.dateCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.dateCreated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.product)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.product.id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.itemId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Magazin_Bijoux/Views/CartItems/Edit.cshtml
@model Magazin_Bijoux.Models.CartItem

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>CartItem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="itemId" />
            <div class="form-group">
                <label asp-for="cartId" class="control-label"></label>
                <select asp-for="cartId" class="form-control" asp-items="ViewBag.cartId"></select>
                <span asp-validation-for="cartId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="quantity" class="control-label"></label>
                <input asp-for="quantity" class="form-control" />
                <span asp-validation-for="quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="dateCreated" class="control-label"></label>
                <input asp-for="dateCreated" class="form-control" />
                <span asp-validation-for="dateCreated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="productId" class="control-label"></label>
                <select asp-for="productId" class="form-control" asp-items="ViewBag.productId"></select>
                <span asp-validation-for="productId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Magazin_Bijoux/Views/CartItems/Index.cshtml
@model IEnumerable<Magazin_Bijoux.Models.CartItem>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.itemId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cartId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.dateCreated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.product)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.itemId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cartId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dateCreated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.product.id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.itemId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.itemId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.itemId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>