Magazin_Bijoux/Controllers/CartItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Magazin_Bijoux.Data;
using Magazin_Bijoux.Models;
using Microsoft.Extensions.Localization;

namespace Magazin_Bijoux.Controllers
{
    public class CartItemsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IStringLocalizer<SharedResource> _sharedLocalizer;

        public string ShoppingCartId { get; set; }

        public CartItemsController(ApplicationDbContext context, IStringLocalizer<SharedResource> sharedLocalizer)
        {
            _context = context;
            _sharedLocalizer = sharedLocalizer;
        }
        public const string CartSessionKey = "CartId";
 
        // GET: CartItems
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.CartItem.Include(c => c.product);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: CartItems/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cartItem = await _context.CartItem
                .Include(c => c.product)
                .FirstOrDefaultAsync(m => m.itemId == id);
            if (cartItem == null)
            {
                return NotFound();
            }

            return View(cartItem);
        }

        // GET: CartItems/Create
        public IActionResult Create()
        {
            ViewData["productId"] = new SelectList(_context.Product, "id", "id");
            return View();
        }

        // POST: CartItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("itemId,cartId,quantity,dateCreated,productId")] CartItem cartItem)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cartItem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["productId"] = new SelectList(_context.Product, "id", "id", cartItem.productId);
            return View(cartItem);
        }

        // GET: CartItems/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cartItem = await _context.CartItem.FindAsync(id);
            if (cartItem == null)
            {
                return NotFound();
            }
            ViewData["productId"] = new SelectList(_context.Product, "id", "id", cartItem.productId);
            return View(cartItem);
        }

        // POST: CartItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("itemId,cartId,quantity,dateCreated,productId")] CartItem cartItem)
        {
            if (id != cartItem.itemId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cartItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CartItemExists(cartItem.itemId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["productId"] = new SelectList(_context.Product, "id", "id", cartItem.productId);
            return View(cartItem);
        }

        // GET: CartItems/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cartItem = await _context.CartItem
                .Include(c => c.product)
                .FirstOrDefaultAsync(m => m.itemId == id);
            if (cartItem == null)
            {
                return NotFound();
            }

            return View(cartItem);
        }

        // POST: CartItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var cartItem = await _context.CartItem.FindAsync(id);
            _context.CartItem.Remove(cartItem);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CartItemExists(string id)
        {
            return _context.CartItem.Any(e => e.itemId == id);
        }
        public string GetCartId()
        {
            if (!HttpContext.Items.ContainsKey(CartSessionKey))
            {
                if (!string.IsNullOrWhiteSpace(HttpContext.User.Identity.Name))
                {
                    HttpContext.Items.Add(CartSessionKey, HttpContext.User.Identity.Name);
                }
                else
                {
                    // Generate a new random GUID using System.Guid class.     
                    Guid tempCartId = Guid.NewGuid();
                    HttpContext.Items.Add(CartSessionKey, tempCartId);
                }
            }
            return HttpContext.Items[CartSessionKey].ToString();
        }
        public List<CartItem> GetCartItems()
        {

            ShoppingCartId = GetCartId();

            return _context.CartItem.Where(
                c => c.cartId == ShoppingCartId).Include(c=>c.product).ToList();
        }
        public ViewResult Cart()
        {
            var cartContext = GetCartItems();
            foreach (var item in cartContext)
            {
                item.product.name = _sharedLocalizer[item.product.name];
                item.product.details = _sharedLocalizer[item.product.details];
                item.product.color = _sharedLocalizer[item.product.color];
            }
            return View(cartContext);
        }

        public void AddToCart(string id)
        {
            // Retrieve the product from the database.           
            ShoppingCartId = GetCartId();

            var cartItem = _context.CartItem.SingleOrDefault(
                c => c.cartId == ShoppingCartId
                && c.productId == id);
            if (cartItem == null)
            {
                // Create a new cart item if no cart item exists.                 
                cartItem = new CartItem
                {
                    itemId = Guid.NewGuid().ToString(),
                    productId = id,
                    cartId = ShoppingCartId,
                    product = _context.Product.SingleOrDefault(
                   p => p.id == id),
                    quantity = 1,
                    dateCreated = DateTime.Now
                };

                _context.CartItem.Add(cartItem);
            }
            else
            {
                // If the item does exist in the cart,                  
                // then add one to the quantity.                 
                cartItem.quantity++;
            }
            _context.SaveChanges();
        }
        public void RemoveFromCart(string id)
        {
            ShoppingCartId = GetCartId();
            var cartItem = _context.CartItem.SingleOrDefault(
                c => c.cartId == ShoppingCartId
                && c.productId == id);
            cartItem.quantity--;
            if (cartItem.quantity <= 0) _context.CartItem.Remove(cartItem);
            _context.SaveChanges();
        }
        public async Task<IActionResult> AddToCartAndReturn(string id, string action, string controller, int quantity, bool hasParameter)
        {
            for (int i = 0; i < quantity; i++)
            {
                AddToCart(id);
            }
            if (hasParameter == true)
                return RedirectToAction(action, controller, new { id = id });
            return RedirectToAction(action, controller);
        }
        public async Task<IActionResult> RemoveFromCartAndReturn(string id, string action, string controller, bool hasParameter)
        {
            RemoveFromCart(id);
            if (hasParameter == true)
                return RedirectToAction(action, controller, new { id = id });
            return RedirectToAction(action, controller);
        }
        public async Task<IActionResult> DeleteFromCart(string id, string action, string controller)
        {
            var cartItem = await _context.CartItem.FindAsync(id);
            _context.CartItem.Remove(cartItem);
            await _context.SaveChangesAsync();
            return RedirectToAction(action, controller);
        }
    }
}

Magazin_Bijoux/Controllers/HomeController.cs
using Magazin_Bijoux.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Magazin_Bijoux.Data;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;

namespace Magazin_Bijoux.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IStringLocalizer<SharedResource> _sharedLocalizer;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context, IStringLocalizer<SharedResource> sharedLocalizer)
        {
            _logger = logger;
            _context = context;
            _sharedLocalizer = sharedLocalizer;
        }
        private readonly ApplicationDbContext _context;

       
        public async Task<IActionResult> Index()
        {
            var productContext = await _context.Product.ToListAsync();
            foreach (var item in productContext)
            {
                item.name = _sharedLocalizer[item.name];
                item.details = _sharedLocalizer[item.details];
                item.color = _sharedLocalizer[item.color];
            }
            return View(productContext);
        }

        public IActionResult About()
        {
            return View();
        }
        public IActionResult LegalPage()
        {
            return View();
        }
        public async Task<IActionResult> Shop()
        {
            var productContext = await _context.Product.ToListAsync();
            foreach (var item in productContext)
            {
                item.name = _sharedLocalizer[item.name];
                item.details = _sharedLocalizer[item.details];
                item.color = _sharedLocalizer[item.color];
            }
            return View(productContext);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Magazin_Bijoux/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Magazin_Bijoux.Data;
using Magazin_Bijoux.Models;
using Microsoft.Extensions.Localization;

namespace Magazin_Bijoux.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IStringLocalizer<SharedResource> _sharedLocalizer;

        public ProductsController(ApplicationDbContext context, IStringLocalizer<SharedResource> sharedLocalizer)
        {
            _context = context;
            _sharedLocalizer = sharedLocalizer;
        }

        public IActionResult GetTime()
        {
            var currentTime = DateTime.Now.ToString("HH:mm:ss");
            return Json(currentTime);
        }
        // GET: Products
        public async Task<IActionResult> Index()
        {
            return View(await _context.Product.ToListAsync());
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }
        public async Task<IActionResult> Product(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.id == id);
            if (product == null)
            {
                return NotFound();
            }

            product.name = _sharedLocalizer[product.name];
            product.details = _sharedLocalizer[product.details];
            product.color = _sharedLocalizer[product.color];

            return View(product);
        }
        public void Decrement(string id)
        {
            ViewBag.quantity=1;
        }
        public async Task<IActionResult> Increment(string id)
        {
            ViewBag.quantity++;
            return RedirectToAction("Product", id);
        }
        // GET: Products/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,name,details,size,color,price,imageURL")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("id,name,details,size,color,price,imageURL")] Product product)
        {
            if (id != product.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var product = await _context.Product.FindAsync(id);
            _context.Product.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(string id)
        {
            return _context.Product.Any(e => e.id == id);
        }
        void DecrementCount()
        {
            if (ViewBag.quantity > 1)
                ViewBag.quantity--;
        }
    }
}

Magazin_Bijoux/Views/Home/About.cshtml
@{
    ViewData["Title"] = @localizer["about"];
}
<head>
    <link rel="stylesheet" href="~/css/about.css" />
</head>
<section class="upper__info">
    @localizer["about us"]
</section>
<section class="middle__info">
    <div class="middle__image">
        <img src="~/MOFT-bijuterii.png" alt="MOFT-bijuterii" />
    </div>
    <div class="middle__text">
        @localizer["bijoux"]
    </div>
</section>
<section class="footer__info">
    <div class="footer__text">
        @localizer["about product"]
    </div>
    <div class="footer__image">
        <img src="~/MOFT-despre.jpg" alt="MOFT-despre.jpg" />
    </div>
</section>

Magazin_Bijoux/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@model IEnumerable<Magazin_Bijoux.Models.Product>
@{
    ViewData["Title"] = "Home";
}
<head>
    <link rel="stylesheet" href="~/css/home.css" />
</head>
<section class="home__showcase">
    <div class="home__arrow">
        <img src="~/Icons/Arrow_left.png" alt="leftArrow" />
    </div>@**@
    <div class="home__items">
        @foreach (var item in Model)
        {
            <div class="home__card">
                <div class="card__image">
                    <a asp-controller="Products" asp-action="Product" asp-route-id="@item.id" class="card__image">
                        <img src=@String.Format("/Product_img280x373/{0}.png", item.imageURL) alt="cardImage.png" />
                    </a>
                </div>
                <div class="card__text">@Html.DisplayFor(modelItem => item.name)</div>
                <div class="card__text">$@Html.DisplayFor(modelItem => item.price)</div>
                @if (SignInManager.IsSignedIn(User))
                {
                    <form asp-controller="CartItems" asp-action="AddToCartAndReturn" asp-route-id="@item.id">
                        <input type="hidden" name="action" value="Index" />
                        <input type="hidden" name="controller" value="Home" />
                        <input type="hidden" name="quantity" value=1 />
                        <input type="hidden" name="hasParameter" value="false" />
                        <div class="form-group">
                            <input type="submit" value="@localizer["add to cart"]" class="card__button btn btn-primary" />
                        </div>
                    </form>
                }
                else
                {
                    <div class="form-group">
                        <a class="card__button btn btn-primary" asp-area="Identity" asp-page="/Account/Login">@localizer["add to cart"]</a>
                    </div>
                }
            </div>
            if (item.id.Contains('4')) break;
        }
    </div>

    <div class="home__arrow">
        <img src="~/Icons/Arrow_right.png" alt="rightArrow.png" />
    </div>
</section>

<section class="home__info">
    <div class="info__container">
        <div class="info__text">
            @localizer["Home Info"]
        </div>

        <a class="info__button" style="margin-top:10px;" asp-area="" asp-controller="Home" asp-action="Shop">@localizer["shop now"]</a>
    </div>
    <div class="info__image">
        <img src="~/Description_Cut.png" alt="footer.jpg" />
    </div>
</section>

Magazin_Bijoux/Views/Home/LegalPage.cshtml
@{
    ViewData["Title"] = localizer["legal page"];
}
<head>
    <link rel="stylesheet" href="~/css/aviz.css" />
</head>
<div>
    @localizer["selling conditions"]
    <div class="text__container">
        <div class="text__wrapper">
            @localizer["product"]
        </div>
        <div class="text__wrapper">
            @localizer["order"]
        </div>
        <div class="text__wrapper">
            @localizer["confirmation"]
        </div>
        <div class="text__wrapper">
            @localizer["payment"]
        </div>
    </div>
</div>

Magazin_Bijoux/Views/Home/Shop.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@model IEnumerable<Magazin_Bijoux.Models.Product>

@{
    ViewData["Title"] = localizer["shop"];
}
<head>
    <link rel="stylesheet" href="~/css/home.css" />
</head>
<section class="home__showcase">

    <div class="home__items">
        @foreach (var item in Model)
        {
        <div class="home__card">
            <a asp-controller="Products" asp-action="Product" asp-route-id="@item.id" class="card__image">
                <img src="@String.Format("/Product_img280x373/{0}.png", item.imageURL)" alt="cardImage.png" />
            </a>
            <div class="card__text">@Html.DisplayFor(modelItem => item.name)</div>
            <div class="card__text">$@Html.DisplayFor(modelItem => item.price)</div>

            @*            <a asp-controller="ShoppingCartActions" asp-action="AddToCart" asp-route-id="@item.id"
        class="card__button" style="margin-top:10px;">Add to cart</a>*@
            @if (SignInManager.IsSignedIn(User))
            {
                <form asp-controller="CartItems" asp-action="AddToCartAndReturn" asp-route-id="@item.id">
                    <input type="hidden" name="action" value="Shop" />
                    <input type="hidden" name="controller" value="Home" />
                    <input type="hidden" name="quantity" value=1 />
                    <input type="hidden" name="hasParameter" value="false" />
                    <div class="form-group">
                        <input type="submit" value="@localizer["add to cart"]" class="card__button btn-primary" />
                    </div>
                </form>
            }
            else
            {
                <div class="form-group">
                    <a class="card__button btn btn-primary" asp-area="Identity" asp-page="/Account/Login">@localizer["add to cart"]</a>
                </div>
            }
        </div>
        }
    </div>

</section>